# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

debug = True
threading_enabled = True

def options (opt):
    opt.load ('compiler_c compiler_cxx')
    opt.load ('boost')

def configure (env):
    env.load ('compiler_c compiler_cxx')
    env.load ('boost')

    env.check(header_name='string.h')
    env.check(function_name='memmem', header_name='string.h', mandatory=False)
    env.check(function_name='stpncpy', header_name='string.h', mandatory=False)

# comment out the following two lines if compiling not on lnxsrv
#    env.options.boost_includes = '/u/cs/grad/yingdi/boost/include'
#    env.options.boost_libs     = '/u/cs/grad/yingdi/boost/lib'
#

    env.check_boost(lib='system thread')

    if debug:
        env.add_supported_cxxflags (cxxflags = ['-I..' , '-O3', '-g3', '-Wall', '-Wextra', '-pedantic', '-Wold-style-cast',
                                            '-Woverloaded-virtual', '-Wctor-dtor-privacy', '-Wconversion',
                                            '-Wfloat-equal','-Wformat=2', '-Winit-self', '-Winline',
                                            '-Wmissing-include-dirs', '-Wredundant-decls', '-Wshadow', '-Wstack-protector', 
                                            '-Wstrict-null-sentinel', '-Wswitch-default', '-Wswitch-enum', '-Winvalid-pch',
                                            '-Wstrict-aliasing=2', '-Wunknown-pragmas', '-Wundef', '-Wlarger-than-len',
                                            '-Wunsafe-loop-optimizations', '-Wpointer-arith', '-Wcast-qual', 
                                            '-Wwrite-strings', '-Winline', '-Wvolatile-register-var', '-Wno-unused-parameter',
                                            '-Wno-variadic-macros'])
    else:
        env.add_supported_cxxflags (cxxflags = ['-I..', '-Wall', 
                                            '-fcolor-diagnostics', '-Wunused-arguments', 
                                            '-Werror'])

def build (env):
    env.load ('compiler_c compiler_cxx')
    env.load ('boost')

    server = env.program (
        target = "http-proxy",
        features = ["cxx", "cxxprogram"],
        use = 'BOOST BOOST_SYSTEM BOOST_THREAD',
        source = [
            # Put additional files here
            # ...
            #
            "compat.cc", # OSX 10.6 compatibility
            "main.cpp",
            "http-headers.cc",
            "http-request.cc",
            "http-response.cc",
            "http-server.cpp",
            "http-client.cpp",
            "http-cache.cpp",
            "http-util.cpp",
            "my_stdio.cpp"
            ]
        )

from waflib import Configure
@Configure.conf
def add_supported_cxxflags(self, cxxflags):
    """
    Check which cxxflags are supported by compiler and add them to env.CXXFLAGS variable
    """
    self.start_msg('Checking allowed flags for c++ compiler')

    supportedFlags = []
    for flag in cxxflags:
        if self.check_cxx (cxxflags=[flag], mandatory=False):
            supportedFlags += [flag]

    self.end_msg (' '.join (supportedFlags))
    self.env.CXXFLAGS += supportedFlags
